version: '3'

services:
  app:
    build:
      context: .
    image: 'stc-file-manager:latest'
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FileManager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Asset99a
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  db:
    image: 'postgres:15.3-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Asset99a
      - POSTGRES_DB=FileManager